version: "3.9"

services:
  app:
    build: .
    container_name: atividade_1
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

